version: '3.8'
services:
  app:
    build: .
    container_name: reddit-crawler
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn src.services:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1 