version: "3.9"

# Development overrides applied on top of docker-compose.yml.
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

services:
  backend:
    command: >-
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    volumes:
      - ./backend:/app

  frontend:
    build: null  # disable production build image
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend
